let arr = [1, 2, 3, 4, 5, "Hello", "this", "is", "Adeel", "Farooq", true, null, { key: "value" }];

console.log(arr.length);
console.log(arr.toString());
console.log(arr.join(" - "));
console.log(arr.pop());
console.log(arr.push("Developer"));
console.log(arr.shift());
console.log(arr.unshift(0));
console.log(arr.slice(1, 4));
console.log(arr.splice(2, 2, "X", "Y"));
console.log(arr.indexOf(3));
console.log(arr.includes("Adeel"));
console.log(arr.reverse());
console.log(arr.sort());
console.log(arr.concat([6, 7, 8]));
console.log(arr.filter(el => typeof el === "number"));
console.log(arr.map(x => x + "!!!"));
console.log(arr.reduce((acc, val) => acc + (typeof val === "number" ? val : 0), 0));
console.log(arr.some(el => typeof el === "string"));
console.log(arr.every(el => typeof el === "number"));
console.log(arr.find(el => typeof el === "string"));
console.log(arr.findIndex(el => typeof el === "string"));
console.log(arr.some(el => typeof el === "boolean"));
console.log(arr.find(el => typeof el === "object"));